development:
  adapter: postgresql
  database: cluutch_io_development
  host: localhost
  username: postgres

test:
  adapter: postgresql
  database: cluutch_io_test
  host: localhost
  username: postgres

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
