 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/v2/quotes_submissions", type: :request do
  # V2::QuotesSubmission. As you add validations to V2::QuotesSubmission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      V2::QuotesSubmission.create! valid_attributes
      get v2_quotes_submissions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      quotes_submission = V2::QuotesSubmission.create! valid_attributes
      get v2_quotes_submission_url(v2_quotes_submission)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_v2_quotes_submission_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      quotes_submission = V2::QuotesSubmission.create! valid_attributes
      get edit_v2_quotes_submission_url(v2_quotes_submission)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new V2::QuotesSubmission" do
        expect {
          post v2_quotes_submissions_url, params: { v2_quotes_submission: valid_attributes }
        }.to change(V2::QuotesSubmission, :count).by(1)
      end

      it "redirects to the created v2_quotes_submission" do
        post v2_quotes_submissions_url, params: { v2_quotes_submission: valid_attributes }
        expect(response).to redirect_to(v2_quotes_submission_url(@v2_quotes_submission))
      end
    end

    context "with invalid parameters" do
      it "does not create a new V2::QuotesSubmission" do
        expect {
          post v2_quotes_submissions_url, params: { v2_quotes_submission: invalid_attributes }
        }.to change(V2::QuotesSubmission, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post v2_quotes_submissions_url, params: { v2_quotes_submission: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested v2_quotes_submission" do
        quotes_submission = V2::QuotesSubmission.create! valid_attributes
        patch v2_quotes_submission_url(v2_quotes_submission), params: { v2_quotes_submission: new_attributes }
        quotes_submission.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the v2_quotes_submission" do
        quotes_submission = V2::QuotesSubmission.create! valid_attributes
        patch v2_quotes_submission_url(v2_quotes_submission), params: { v2_quotes_submission: new_attributes }
        quotes_submission.reload
        expect(response).to redirect_to(v2_quotes_submission_url(quotes_submission))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        quotes_submission = V2::QuotesSubmission.create! valid_attributes
        patch v2_quotes_submission_url(v2_quotes_submission), params: { v2_quotes_submission: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested v2_quotes_submission" do
      quotes_submission = V2::QuotesSubmission.create! valid_attributes
      expect {
        delete v2_quotes_submission_url(v2_quotes_submission)
      }.to change(V2::QuotesSubmission, :count).by(-1)
    end

    it "redirects to the v2_quotes_submissions list" do
      quotes_submission = V2::QuotesSubmission.create! valid_attributes
      delete v2_quotes_submission_url(v2_quotes_submission)
      expect(response).to redirect_to(v2_quotes_submissions_url)
    end
  end
end
