swagger: "2.0"
info:
  title: Cluutch API
  description: Daily weed prices by ounce.
  version: 1.0.0
host: api.cluutch.io
basePath: /v3
schemes:
  - https
paths:
  /dailies:
    get:
      summary: Returns the average price for an ounce of weed by day.
      operationId: get-dailies
      x-google-backend:
        address: https://us-central1-cluutch.cloudfunctions.net/get-dailies
      produces:
        - application/json
      responses:
        200:
          description: OK
  /blunt-facts:
    get:
      summary: Returns blunt facts about weed straints, including price and tags.
      operationId: get-blunt-facts
      parameters:
        - in: query
          name: strain
          type: string
          description: The strain to retrieve information about.
          required: true
      x-google-backend:
        address: https://us-central1-cluutch.cloudfunctions.net/get-blunt-facts
      produces:
        - application/json
      responses:
        200:
          description: OK
