swagger: "2.0"
info:
  title: Cluutch API
  description: Daily weed prices by city
  version: 1.0.0
host: api.cluutch.io
basePath: /v3
schemes:
  - https
paths:
  /dailies:
    get:
      summary: Returns the average price for an ounce of weed by day.
      operationId: get-dailies
      x-google-backend:
        address: https://us-central1-cluutch.cloudfunctions.net/get-dailies
      produces:
        - application/json
      responses:
        200:
          description: OK
  /strain:
    get:
      summary: Returnes information about this strain, including price and tags.
      operationId: get-strain-info
      parameters:
        - in: query
          name: strain
          type: string
          description: The strain to retrieve information about.
          required: true
      x-google-backend:
        address: https://us-central1-cluutch.cloudfunctions.net/get-strain-info
      produces:
        - application/json
      responses:
        200:
          description: OK
